#!/bin/sh

function forbidCommitTo {
    branch="$(git rev-parse --abbrev-ref HEAD)"
    if [ "$branch" == "$1" ]; then
	echo "You can't commit directly to $1 branch"
	exit 1
    fi
}

forbidCommitTo "dev"
forbidCommitTo "master"
