PREFIX entity: <http://statistics.data.gov.uk/def/statistical-entity#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?area_code
WHERE {
  ?area_entity entity:code ?area_code_entity;
     rdfs:label ?area_code .
  ?area_code_entity rdfs:label ?area_code_type;
     FILTER(SUBSTR(?area_code_type, 2, 2) > "01").
}
