#!/bin/bash
TOP_DIR=/var/tmp/batch/$(date +%s)   #${PWD}
mkdir ${TOP_DIR}
cd ${TOP_DIR}

RUNDIR=${1}
echo "Generating batchable from ${1} (working directory is ${TOP_DIR})"

# Check if the main file exists
ls $RUNDIR/run.py &> /dev/null
if [[ $? -ne 0 ]];
then
    ls $RUNDIR/run.py
    return 1
fi
echo "Found run.py"

# Prepare the run directory
mkdir run/
cp $RUNDIR/run.py run/

# Copy dependencies
DEPCOUNTER=0
for DIR_TO_COPY in "${@:2}"
do
    ((DEPCOUNTER++))
    echo $DIR_TO_COPY
    ls $DIR_TO_COPY &> /dev/null
    if [[ $? -ne 0 ]];
    then
        rm -rf run/
        ls $DIR_TO_COPY
	rmdir ${TOP_DIR}
        return 1
    fi
    echo "Doing 'cp -r ${DIR_TO_COPY} run/'"
    cp -r ${DIR_TO_COPY} run/
done
find run/ -name "*.pyc" -exec rm -f {} \;
find run/ -name "*.~" -exec rm -f {} \;
find run/ -name "*out" -exec rm -f {} \;
find run/ -name "*log" -exec rm -f {} \;
find run/ -name "*#" -exec rm -f {} \;
echo "Added $DEPCOUNTER objects to the environment"

# Generate pip requirements
pip install pipreqs &> /dev/null
pipreqs run

# Zip it up and copy to s3
echo "Will zip up the following environment:"
tree run/
zip -r run.zip run/
FILE_TIMESTAMP=run-$(date +%s%N).zip
echo "Pushing to s3"
aws s3 cp run.zip s3://nesta-batch/${FILE_TIMESTAMP}

# Tidy up
rm run.zip
rm -r run/

# Echo the file name
echo ${FILE_TIMESTAMP}
rmdir ${TOP_DIR}
