'''Automatically generated by pypatstat (https://github.com/nestauk/pypatstat)'''

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column
from sqlalchemy.types import REAL,NVARCHAR,VARCHAR,INT,CHAR,SMALLINT,DATE

Base = declarative_base()

class Tls201Appln(Base):
	__tablename__ = 'tls201_appln'
	appln_id = Column(INT, primary_key=True, default=0)
	appln_auth = Column(CHAR(2), default='')
	appln_nr = Column(VARCHAR(15), default='')
	appln_kind = Column(CHAR(2), default='  ')
	appln_filing_date = Column(DATE, default='9999-12-31')
	appln_filing_year = Column(SMALLINT, default=9999)
	appln_nr_epodoc = Column(VARCHAR(20), default='')
	appln_nr_original = Column(VARCHAR(100), default='')
	ipr_type = Column(CHAR(2), default='')
	receiving_office = Column(CHAR(2), default='')
	internat_appln_id = Column(INT, default=0)
	int_phase = Column(CHAR(1), default='N')
	reg_phase = Column(CHAR(1), default='N')
	nat_phase = Column(CHAR(1), default='N')
	earliest_filing_date = Column(DATE, default='9999-12-31')
	earliest_filing_year = Column(SMALLINT, default=9999)
	earliest_filing_id = Column(INT, default=0)
	earliest_publn_date = Column(DATE, default='9999-12-31')
	earliest_publn_year = Column(SMALLINT, default=9999)
	earliest_pat_publn_id = Column(INT, default=0)
	granted = Column(CHAR(1), default='N')
	docdb_family_id = Column(INT, default=0)
	inpadoc_family_id = Column(INT, default=0)
	docdb_family_size = Column(SMALLINT, default=0)
	nb_citing_docdb_fam = Column(SMALLINT, default=0)
	nb_applicants = Column(SMALLINT, default=0)
	nb_inventors = Column(SMALLINT, default=0)


class Tls202ApplnTitle(Base):
	__tablename__ = 'tls202_appln_title'
	appln_id = Column(INT, primary_key=True, default=0)
	appln_title_lg = Column(CHAR(2), default='')
	appln_title = Column(NVARCHAR(100000))


class Tls203ApplnAbstr(Base):
	__tablename__ = 'tls203_appln_abstr'
	appln_id = Column(INT, primary_key=True, default=0)
	appln_abstract_lg = Column(CHAR(2), default='')
	appln_abstract = Column(NVARCHAR(100000), default='')


class Tls204ApplnPrior(Base):
	__tablename__ = 'tls204_appln_prior'
	appln_id = Column(INT, primary_key=True, default=0)
	prior_appln_id = Column(INT, primary_key=True, default=0)
	prior_appln_seq_nr = Column(SMALLINT, default=0)


class Tls205TechRel(Base):
	__tablename__ = 'tls205_tech_rel'
	appln_id = Column(INT, primary_key=True, default=0)
	tech_rel_appln_id = Column(INT, primary_key=True, default=0)


class Tls206Person(Base):
	__tablename__ = 'tls206_person'
	person_id = Column(INT, primary_key=True, default=0)
	person_name = Column(NVARCHAR(500), default='')
	person_name_orig_lg = Column(NVARCHAR(500), default='')
	person_address = Column(NVARCHAR(1000), default='')
	person_ctry_code = Column(CHAR(2), default='')
	doc_std_name_id = Column(INT, default=0)
	doc_std_name = Column(NVARCHAR(500), default='')
	psn_id = Column(INT, default=0)
	psn_name = Column(NVARCHAR(500), default='')
	psn_level = Column(SMALLINT, default=0)
	psn_sector = Column(VARCHAR(50), default='')


class Tls207PersAppln(Base):
	__tablename__ = 'tls207_pers_appln'
	person_id = Column(INT, primary_key=True, default=0)
	appln_id = Column(INT, primary_key=True, default=0)
	applt_seq_nr = Column(SMALLINT, primary_key=True, default=0)
	invt_seq_nr = Column(SMALLINT, primary_key=True, default=0)


class Tls209ApplnIpc(Base):
	__tablename__ = 'tls209_appln_ipc'
	appln_id = Column(INT, primary_key=True, default=0)
	ipc_class_symbol = Column(VARCHAR(15), primary_key=True, default='')
	ipc_class_level = Column(CHAR(1), default='')
	ipc_version = Column(DATE, default='9999-12-31')
	ipc_value = Column(CHAR(1), default='')
	ipc_position = Column(CHAR(1), default='')
	ipc_gener_auth = Column(CHAR(2), default='')


class Tls210ApplnNCls(Base):
	__tablename__ = 'tls210_appln_n_cls'
	appln_id = Column(INT, primary_key=True, default=0)
	nat_class_symbol = Column(NVARCHAR(15), primary_key=True, default='')


class Tls211PatPubln(Base):
	__tablename__ = 'tls211_pat_publn'
	pat_publn_id = Column(INT, primary_key=True, default=0)
	publn_auth = Column(CHAR(2), default='')
	publn_nr = Column(VARCHAR(15), default='')
	publn_nr_original = Column(VARCHAR(100), default='')
	publn_kind = Column(CHAR(2), default='')
	appln_id = Column(INT, default=0)
	publn_date = Column(DATE, default='9999-12-31')
	publn_lg = Column(CHAR(2), default='')
	publn_first_grant = Column(CHAR(1), default='N')
	publn_claims = Column(SMALLINT, default=0)


class Tls212Citation(Base):
	__tablename__ = 'tls212_citation'
	pat_publn_id = Column(INT, primary_key=True, default=0)
	citn_replenished = Column(INT, primary_key=True, default=0)
	citn_id = Column(SMALLINT, primary_key=True, default=0)
	citn_origin = Column(CHAR(3), default='')
	cited_pat_publn_id = Column(INT, default=0)
	cited_appln_id = Column(INT, default=0)
	pat_citn_seq_nr = Column(SMALLINT, default=0)
	cited_npl_publn_id = Column(INT, default=0)
	npl_citn_seq_nr = Column(SMALLINT, default=0)
	citn_gener_auth = Column(CHAR(2), default='')


class Tls214NplPubln(Base):
	__tablename__ = 'tls214_npl_publn'
	npl_publn_id = Column(INT, primary_key=True, default=0)
	npl_type = Column(CHAR(1), default='')
	npl_biblio = Column(NVARCHAR(100000), default='')
	npl_author = Column(NVARCHAR(1000), default='')
	npl_title1 = Column(NVARCHAR(1000), default='')
	npl_title2 = Column(NVARCHAR(1000), default='')
	npl_editor = Column(NVARCHAR(500), default='')
	npl_volume = Column(NVARCHAR(50), default='')
	npl_issue = Column(NVARCHAR(50), default='')
	npl_publn_date = Column(VARCHAR(8), default='')
	npl_publn_end_date = Column(VARCHAR(8), default='')
	npl_publisher = Column(NVARCHAR(500), default='')
	npl_page_first = Column(VARCHAR(200), default='')
	npl_page_last = Column(VARCHAR(200), default='')
	npl_abstract_nr = Column(VARCHAR(50), default='')
	npl_doi = Column(VARCHAR(500), default='')
	npl_isbn = Column(VARCHAR(30), default='')
	npl_issn = Column(VARCHAR(30), default='')
	online_availability = Column(VARCHAR(500), default='')
	online_classification = Column(VARCHAR(35), default='')
	online_search_date = Column(VARCHAR(8), default='')


class Tls215CitnCateg(Base):
	__tablename__ = 'tls215_citn_categ'
	pat_publn_id = Column(INT, primary_key=True, default=0)
	citn_replenished = Column(INT, primary_key=True, default=0)
	citn_id = Column(SMALLINT, primary_key=True, default=0)
	citn_categ = Column(NVARCHAR(10), primary_key=True, default='')
	relevant_claim = Column(SMALLINT, primary_key=True, default=0)


class Tls216ApplnContn(Base):
	__tablename__ = 'tls216_appln_contn'
	appln_id = Column(INT, primary_key=True, default=0)
	parent_appln_id = Column(INT, primary_key=True, default=0)
	contn_type = Column(CHAR(3), default='')


class Tls222ApplnJpClass(Base):
	__tablename__ = 'tls222_appln_jp_class'
	appln_id = Column(INT, primary_key=True, default=0)
	jp_class_scheme = Column(VARCHAR(5), primary_key=True, default='')
	jp_class_symbol = Column(VARCHAR(50), primary_key=True, default='')


class Tls223ApplnDocus(Base):
	__tablename__ = 'tls223_appln_docus'
	appln_id = Column(INT, primary_key=True, default=0)
	docus_class_symbol = Column(VARCHAR(50), primary_key=True, default='')


class Tls224ApplnCpc(Base):
	__tablename__ = 'tls224_appln_cpc'
	appln_id = Column(INT, primary_key=True, default=0)
	cpc_class_symbol = Column(VARCHAR(19), primary_key=True, default='')
	cpc_scheme = Column(VARCHAR(5), primary_key=True, default='')
	cpc_version = Column(DATE, default='9999-12-31')
	cpc_value = Column(CHAR(1), default='')
	cpc_position = Column(CHAR(1), default='')
	cpc_gener_auth = Column(CHAR(2), default='')


class Tls226PersonOrig(Base):
	__tablename__ = 'tls226_person_orig'
	person_orig_id = Column(INT, primary_key=True, default=0)
	person_id = Column(INT, default=0)
	source = Column(CHAR(5), default='')
	source_version = Column(VARCHAR(10), default='')
	name_freeform = Column(NVARCHAR(500), default='')
	person_name_orig_lg = Column(NVARCHAR(500), default='')
	last_name = Column(NVARCHAR(500), default='')
	first_name = Column(NVARCHAR(500), default='')
	middle_name = Column(NVARCHAR(500), default='')
	address_freeform = Column(NVARCHAR(1000), default='')
	address_1 = Column(NVARCHAR(500), default='')
	address_2 = Column(NVARCHAR(500), default='')
	address_3 = Column(NVARCHAR(500), default='')
	address_4 = Column(NVARCHAR(500), default='')
	address_5 = Column(NVARCHAR(500), default='')
	street = Column(NVARCHAR(500), default='')
	city = Column(NVARCHAR(200), default='')
	state = Column(CHAR(2), default='')
	person_ctry_code = Column(CHAR(2), default='')
	residence_ctry_code = Column(CHAR(2), default='')
	role = Column(VARCHAR(2), default='')


class Tls227PersPubln(Base):
	__tablename__ = 'tls227_pers_publn'
	person_id = Column(INT, primary_key=True, default=0)
	pat_publn_id = Column(INT, primary_key=True, default=0)
	applt_seq_nr = Column(SMALLINT, primary_key=True, default=0)
	invt_seq_nr = Column(SMALLINT, primary_key=True, default=0)


class Tls228DocdbFamCitn(Base):
	__tablename__ = 'tls228_docdb_fam_citn'
	docdb_family_id = Column(INT, primary_key=True, default=0)
	cited_docdb_family_id = Column(INT, primary_key=True, default=0)


class Tls229ApplnNace2(Base):
	__tablename__ = 'tls229_appln_nace2'
	appln_id = Column(INT, primary_key=True, default=0)
	nace2_code = Column(VARCHAR(5), primary_key=True, default='')
	weight = Column(REAL)


class Tls230ApplnTechnField(Base):
	__tablename__ = 'tls230_appln_techn_field'
	appln_id = Column(INT, primary_key=True, default=0)
	techn_field_nr = Column(SMALLINT, primary_key=True, default=0)
	weight = Column(REAL)


class Tls231InpadocLegalEvent(Base):
	__tablename__ = 'tls231_inpadoc_legal_event'
	event_id = Column(INT, primary_key=True, default=0)
	appln_id = Column(INT, default=0)
	event_seq_nr = Column(SMALLINT, default=0)
	event_type = Column(CHAR(3), default='	')
	event_auth = Column(CHAR(2), default='  ')
	event_code = Column(VARCHAR(4), default='')
	event_filing_date = Column(DATE, default='9999-12-31')
	event_publn_date = Column(DATE, default='9999-12-31')
	event_effective_date = Column(DATE, default='9999-12-31')
	event_text = Column(VARCHAR(1000), default='')
	ref_doc_auth = Column(CHAR(2), default='  ')
	ref_doc_nr = Column(VARCHAR(20), default='')
	ref_doc_kind = Column(CHAR(2), default='  ')
	ref_doc_date = Column(DATE, default='9999-12-31')
	ref_doc_text = Column(VARCHAR(1000), default='')
	party_type = Column(VARCHAR(3), default='	')
	party_seq_nr = Column(SMALLINT, default=0)
	party_new = Column(VARCHAR(1000), default='')
	party_old = Column(VARCHAR(1000), default='')
	spc_nr = Column(VARCHAR(40), default='')
	spc_filing_date = Column(DATE, default='9999-12-31')
	spc_patent_expiry_date = Column(DATE, default='9999-12-31')
	spc_extension_date = Column(DATE, default='9999-12-31')
	spc_text = Column(VARCHAR(1000), default='')
	designated_states = Column(VARCHAR(1000), default='')
	extension_states = Column(VARCHAR(30), default='')
	fee_country = Column(CHAR(2), default='  ')
	fee_payment_date = Column(DATE, default='9999-12-31')
	fee_renewal_year = Column(SMALLINT, default=9999)
	fee_text = Column(VARCHAR(1000), default='')
	lapse_country = Column(CHAR(2), default='  ')
	lapse_date = Column(DATE, default='9999-12-31')
	lapse_text = Column(VARCHAR(1000), default='')
	reinstate_country = Column(CHAR(2), default='  ')
	reinstate_date = Column(DATE, default='9999-12-31')
	reinstate_text = Column(VARCHAR(1000), default='')
	class_scheme = Column(VARCHAR(4), default='')
	class_symbol = Column(VARCHAR(50), default='')


class Tls801Country(Base):
	__tablename__ = 'tls801_country'
	ctry_code = Column(CHAR(2), primary_key=True, default='')
	iso_alpha3 = Column(CHAR(3), default='')
	st3_name = Column(VARCHAR(100), default='')
	state_indicator = Column(CHAR(1), default='')
	continent = Column(VARCHAR(25), default='')
	eu_member = Column(CHAR(1), default='')
	epo_member = Column(CHAR(1), default='')
	oecd_member = Column(CHAR(1), default='')
	discontinued = Column(CHAR(1), default='')


class Tls803LegalEventCode(Base):
	__tablename__ = 'tls803_legal_event_code'
	event_auth = Column(CHAR(2), primary_key=True, default='')
	event_code = Column(VARCHAR(4), primary_key=True, default='')
	event_impact = Column(CHAR(1), default='')
	event_descr = Column(VARCHAR(250), default='')
	event_descr_orig = Column(VARCHAR(250), default='')
	event_category_code = Column(CHAR(1), default='')
	event_category_title = Column(VARCHAR(100), default='')


class Tls901TechnFieldIpc(Base):
	__tablename__ = 'tls901_techn_field_ipc'
	ipc_maingroup_symbol = Column(VARCHAR(8), primary_key=True, default='')
	techn_field_nr = Column(SMALLINT, default=0)
	techn_sector = Column(VARCHAR(50), default='')
	techn_field = Column(VARCHAR(50), default='')


class Tls902IpcNace2(Base):
	__tablename__ = 'tls902_ipc_nace2'
	ipc = Column(VARCHAR(8), primary_key=True, default='')
	not_with_ipc = Column(VARCHAR(8), primary_key=True, default='')
	unless_with_ipc = Column(VARCHAR(8), primary_key=True, default='')
	nace2_code = Column(VARCHAR(5), primary_key=True, default='')
	nace2_weight = Column(SMALLINT)
	nace2_descr = Column(VARCHAR(150), default='')


class Tls904Nuts(Base):
	__tablename__ = 'tls904_nuts'
	nuts = Column(VARCHAR(5), primary_key=True, default='')
	nuts_level = Column(SMALLINT, default=0)
	nuts_label = Column(NVARCHAR(250), default='')


class Tls906Person(Base):
	__tablename__ = 'tls906_person'
	person_id = Column(INT, primary_key=True, default=0)
	person_name = Column(NVARCHAR(500), default='')
	person_name_orig_lg = Column(NVARCHAR(500), default='')
	person_address = Column(NVARCHAR(1000), default='')
	person_ctry_code = Column(CHAR(2), default='')
	nuts = Column(VARCHAR(5), default='')
	nuts_level = Column(SMALLINT, default=9)
	doc_std_name_id = Column(INT, default=0)
	doc_std_name = Column(NVARCHAR(500), default='')
	psn_id = Column(INT, default=0)
	psn_name = Column(NVARCHAR(500), default='')
	psn_level = Column(SMALLINT, default=0)
	psn_sector = Column(VARCHAR(50), default='')
	han_id = Column(INT, default=0)
	han_name = Column(NVARCHAR(500), default='')
	han_harmonized = Column(INT, default=0)
